# Generated by Django 3.2.1 on 2021-05-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.PositiveSmallIntegerField()),
                ('sex', models.BooleanField(choices=[(True, 'M'), (False, 'F')])),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('is_good', models.BooleanField()),
            ],
        ),
    ]
