# Generated by Django 3.2.1 on 2021-05-05 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.PositiveSmallIntegerField()),
                ('fun_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='dogs.dog')),
            ],
        ),
    ]
